In [1]:
import numpy as np
import pandas as pd
from characters.sparkle import Sparkle
from characters.qingque import Qingque
from characters.silver_wolf import Silver_Wolf
from characters.fu_xuan import Fu_Xuan
from simulations.qingque_mono_quantum_looped import QQ_Mono_Quantum, Initialize_QQ_Mono_Quantum
from utils.arena import Arena
from utils.data_table import Action_Table, Qingque_Statistics_Table, Qingque_Probability_Table

# Character Imports

In [2]:
qingque_speed = 135

In [3]:
silver_wolf_speed = 147

In [4]:
sparkle_speed = 134.1
bronya_lc = False
sparkle_tech = True
sparkle_turn_1_skill = True

In [5]:
fu_xuan_speed = 146
fu_xuan_technique = True

# Simulations

In [6]:
arena, qq, spk, sw, fx = Initialize_QQ_Mono_Quantum(qingque_speed=qingque_speed, fu_xuan_speed=fu_xuan_speed, sparkle_speed=sparkle_speed, silver_wolf_speed=silver_wolf_speed, bronya_lc=bronya_lc)

In [7]:
action_dataframe = Action_Table()
statistics_dataframe = Qingque_Statistics_Table()
probability_dataframe = Qingque_Probability_Table()
trials = 100

In [8]:
ult_sp_threshold = 5
for run in range(trials):
    print(f"\rRun number = {run}", end='')
    arena, qq, spk, sw, fx = Initialize_QQ_Mono_Quantum(qingque_speed=qingque_speed, fu_xuan_speed=fu_xuan_speed, sparkle_speed=sparkle_speed, silver_wolf_speed=silver_wolf_speed, sparkle_turn_1_skill = sparkle_turn_1_skill)
    QQ_Mono_Quantum(arena, qq, spk, sw, fx, action_df=action_dataframe, stat_df= statistics_dataframe, prob_df = probability_dataframe, run_num=run, cycles=5 , ult_sp_threshold = ult_sp_threshold)

Run number = 1

c:\Users\rainf\OneDrive\Documents\Git Projects\HSR_Action_Simulator-1\utils\data_table.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df = pd.concat([self.df, pd.DataFrame([new_row])], ignore_index = True)
c:\Users\rainf\OneDrive\Documents\Git Projects\HSR_Action_Simulator-1\utils\data_table.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df = pd.concat([self.df, pd.DataFrame([new_row])], ignore_index = True)

Run number = 5

Run number = 99

# Results

In [9]:
#statistics_dataframe.df

In [10]:
df = statistics_dataframe.df.copy()
start = df["Turn"].min()
end = df["Turn"].max()
columns = df.columns[1:]
summary_df = pd.DataFrame(columns=columns)
for turn in range(start, end):
    df_copy = df.copy()
    df_turn = df_copy.loc[df["Turn"] == turn]

    new_row_dict = {}
    for col in columns:
        mean = round(df_turn[col].mean(),3)
        std = round(df_turn[col].std(),3)
        if std != 0:
            entry = f"{mean} ± {std}"
        else:
            entry = f"{mean}"
        new_row_dict[col] = [entry]
    new_row = pd.DataFrame.from_dict(new_row_dict)
    summary_df = pd.concat([summary_df, new_row], ignore_index= True)

In [11]:
summary_df_styled = summary_df.style.set_caption(f"Qingque speed = {qingque_speed}, Sparkle speed = {sparkle_speed}, Bronya_LC = {bronya_lc}, Silver Wolf Speed = {silver_wolf_speed}, Fu Xuan speed = {fu_xuan_speed}")
summary_df_styled

In [12]:
action_df = action_dataframe.df

In [13]:
sparkle_action_df = action_df.loc[(action_df["Name"] == "Sparkle")].copy()

In [14]:
sparkle_action_df.iloc[:30]

        Name  Cycle  Action Gauge Current SP  Current Energy    Action SP Gain
3    Sparkle    0.0     74.571216          3           55.00     Skill      -1
7    Sparkle    0.0    149.142431          1           90.82     Skill      -1
8    Sparkle    0.0    149.242431          0          126.64  Ultimate       4
13   Sparkle    1.0    223.713647          3            5.00     Basic       1
17   Sparkle    2.0    298.284862          4           40.82     Skill      -1
21   Sparkle    3.0    372.856078          4           76.64     Skill      -1
22   Sparkle    3.0    372.956078          3          112.46  Ultimate       4
27   Sparkle    3.0    447.427293          5            5.00     Basic       1
31   Sparkle    4.0    521.998509          1           40.82     Skill      -1
35   Sparkle    5.0    596.569724          1           76.64     Skill      -1
36   Sparkle    5.0    596.669724          0          112.46  Ultimate       4
44   Sparkle    0.0     74.571216          7           55.00     Skill      -1
48   Sparkle    0.0    149.142431          6           90.82     Skill      -1
53   Sparkle    1.0    223.713647          7          120.00  Ultimate       4
54   Sparkle    1.0    223.713647         11            5.00     Basic       1
58   Sparkle    2.0    298.284862          5           40.82     Skill      -1
62   Sparkle    3.0    372.856078          1           76.64     Skill      -1
63   Sparkle    3.0    372.956078          0          112.46  Ultimate       4
68   Sparkle    3.0    447.427293         -1            5.00     Basic       1
72   Sparkle    4.0    521.998509         -1           40.82     Basic       1
76   Sparkle    5.0    596.569724          2           76.64     Skill      -1
79   Sparkle    5.0    632.315337         -1          112.46  Ultimate       4
81   Sparkle    6.0    671.140940          3            5.00     Skill      -1
85   Sparkle    0.0     74.571216          3           55.00     Skill      -1
89   Sparkle    0.0    149.142431          3           90.82     Skill      -1
90   Sparkle    0.0    149.242431          2          126.64  Ultimate       4
95   Sparkle    1.0    223.713647          1            5.00     Basic       1
99   Sparkle    2.0    298.284862          1           40.82     Skill      -1
103  Sparkle    3.0    372.856078          1           76.64     Skill      -1
104  Sparkle    3.0    372.956078          0          112.46  Ultimate       4

In [15]:
spk_ult_df = sparkle_action_df.loc[sparkle_action_df["Action"] == "Ultimate"]

In [16]:
len(spk_ult_df.loc[spk_ult_df["Current Energy"] == 120.00])/len(spk_ult_df)

0.3076923076923077

In [17]:
action_df.loc[(action_df["Name"] != "Fu Xuan") & (action_df["Name"] != "Silver Wolf")].iloc[:20]

,Name,Cycle,Action Gauge,Current SP,Current Energy,Action,SP Gain
2,Qingque,0.0,74.074074,7,70.00,Enhanced Basic,4
3,Sparkle,0.0,74.571216,3,55.00,Skill,-1
4,Qingque,0.0,111.211111,2,70.00,Basic,3
7,Sparkle,0.0,149.142431,1,90.82,Skill,-1
8,Sparkle,0.0,149.242431,0,126.64,Ultimate,4
9,Qingque,0.0,149.242431,4,70.00,Enhanced Basic,0
12,Qingque,1.0,223.316505,4,70.00,Enhanced Basic,1
13,Sparkle,1.0,223.713647,3,5.00,Basic,1
16,Qingque,2.0,297.390579,4,70.00,Enhanced Basic,0
17,Sparkle,2.0,298.284862,4,40.82,Skill,-1
18,Qingque,2.0,334.527616,3,70.00,Enhanced Basic,1
21,Sparkle,3.0,372.856078,4,76.64,Skill,-1
22,Sparkle,3.0,372.956078,3,112.46,Ultimate,4
23,Qingque,3.0,372.956078,7,70.00,Enhanced Basic,0
26,Qingque,3.0,447.030152,7,70.00,Enhanced Basic,2
27,Sparkle,3.0,447.427293,5,5.00,Basic,1
30,Qingque,4.0,521.104226,4,70.00,Enhanced Basic,3
31,Sparkle,4.0,521.998509,1,40.82,Skill,-1
34,Qingque,5.0,558.241263,2,70.00,Enhanced Basic,1
35,Sparkle,5.0,596.569724,1,76.64,Skill,-1

In [18]:
statistics_dataframe.df.iloc[:20]

,Sim #,Turn,Cycle,Action Gauge,Current SP,Current Tiles,# Draws,Hidden Hand
0,0,1,0.0,74.074074,7,3,5,True
1,0,2,0.0,111.211111,2,2,3,False
2,0,3,0.0,149.242431,4,6,1,True
3,0,4,1.0,223.316505,4,3,2,True
4,0,5,2.0,297.390579,4,4,1,True
5,0,6,2.0,334.527616,3,2,2,True
6,0,7,3.0,372.956078,7,4,1,True
7,0,8,3.0,447.030152,7,3,3,True
8,0,9,4.0,521.104226,4,4,4,True
9,0,10,5.0,558.241263,2,4,2,True
10,0,11,5.0,596.669724,4,2,2,True
11,0,12,6.0,670.743798,5,3,2,True
12,1,1,0.0,74.074074,7,3,1,True
13,1,2,0.0,111.211111,6,2,3,True
14,1,3,0.0,149.242431,8,4,1,True
15,1,4,1.0,223.316505,8,3,2,True
16,1,5,2.0,297.390579,7,4,3,True
17,1,6,2.0,334.527616,4,2,5,False
18,1,7,3.0,372.956078,4,6,3,True
19,1,8,3.0,447.030152,2,3,3,False