In [1]:
import numpy as np
import pandas as pd
from characters.sparkle import Sparkle
from characters.qingque import Qingque
from characters.silver_wolf import Silver_Wolf
from characters.fu_xuan import Fu_Xuan
from simulations.qingque_mono_quantum_looped import QQ_Mono_Quantum, Initialize_QQ_Mono_Quantum
from utils.arena import Arena
from utils.data_table import Action_Table, Qingque_Statistics_Table, Qingque_Probability_Table

# Character Imports

In [2]:
qingque_speed = 98

In [3]:
silver_wolf_speed = 146

In [4]:
sparkle_speed = 161
bronya_lc = False
sparkle_tech = True
sparkle_turn_1_skill = True

In [5]:
fu_xuan_speed = 142
fu_xuan_technique = True

# Simulations

In [6]:
arena, qq, spk, sw, fx = Initialize_QQ_Mono_Quantum(qingque_speed=qingque_speed, fu_xuan_speed=fu_xuan_speed, sparkle_speed=sparkle_speed, silver_wolf_speed=silver_wolf_speed, bronya_lc=bronya_lc)

In [7]:
action_dataframe = Action_Table()
statistics_dataframe = Qingque_Statistics_Table()
probability_dataframe = Qingque_Probability_Table()
trials = 100

In [8]:
ult_sp_threshold = 5
for run in range(trials):
    print(f"\rRun number = {run}", end='')
    arena, qq, spk, sw, fx = Initialize_QQ_Mono_Quantum(qingque_speed=qingque_speed, fu_xuan_speed=fu_xuan_speed, sparkle_speed=sparkle_speed, silver_wolf_speed=silver_wolf_speed, sparkle_turn_1_skill = sparkle_turn_1_skill)
    QQ_Mono_Quantum(arena, qq, spk, sw, fx, action_df=action_dataframe, stat_df= statistics_dataframe, prob_df = probability_dataframe, run_num=run, cycles=5 , ult_sp_threshold = ult_sp_threshold)

Run number = 1

c:\Users\rainf\OneDrive\Documents\Git Projects\HSR_Action_Simulator-1\utils\data_table.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df = pd.concat([self.df, pd.DataFrame([new_row])], ignore_index = True)
c:\Users\rainf\OneDrive\Documents\Git Projects\HSR_Action_Simulator-1\utils\data_table.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df = pd.concat([self.df, pd.DataFrame([new_row])], ignore_index = True)

Run number = 7

Run number = 99

# Results

In [9]:
#statistics_dataframe.df

In [10]:
df = statistics_dataframe.df.copy()
start = df["Turn"].min()
end = df["Turn"].max()
columns = df.columns[1:]
summary_df = pd.DataFrame(columns=columns)
for turn in range(start, end):
    df_copy = df.copy()
    df_turn = df_copy.loc[df["Turn"] == turn]

    new_row_dict = {}
    for col in columns:
        mean = round(df_turn[col].mean(),3)
        std = round(df_turn[col].std(),3)
        if std != 0:
            entry = f"{mean} ± {std}"
        else:
            entry = f"{mean}"
        new_row_dict[col] = [entry]
    new_row = pd.DataFrame.from_dict(new_row_dict)
    summary_df = pd.concat([summary_df, new_row], ignore_index= True)

In [11]:
summary_df_styled = summary_df.style.set_caption(f"Qingque speed = {qingque_speed}, Sparkle speed = {sparkle_speed},  Silver Wolf Speed = {silver_wolf_speed}, Fu Xuan speed = {fu_xuan_speed}")
summary_df_styled

In [12]:
action_df = action_dataframe.df

In [13]:
sparkle_action_df = action_df.loc[(action_df["Name"] == "Sparkle")].copy()

In [14]:
sparkle_action_df.iloc[:30]

       Name  Cycle  Action Gauge Current SP  Current Energy    Action SP Gain
0   Sparkle    0.0     62.111801          6           55.00     Skill      -1
4   Sparkle    0.0    124.223602          4           90.82     Skill      -1
5   Sparkle    0.0    124.323602          3          126.64  Ultimate       4
9   Sparkle    1.0    186.335404          4            5.00     Skill      -1
13  Sparkle    1.0    248.447205          1           40.82     Skill      -1
17  Sparkle    2.0    310.559006          1           76.64     Skill      -1
18  Sparkle    2.0    310.659006          0          112.46  Ultimate       4
22  Sparkle    3.0    372.670807          2            5.00     Skill      -1
26  Sparkle    3.0    434.782609          1           40.82     Skill      -1
30  Sparkle    4.0    496.894410          1           76.64     Skill      -1
31  Sparkle    4.0    496.994410          0          112.46  Ultimate       4
34  Sparkle    5.0    559.006211          2            5.00     Skill      -1
38  Sparkle    5.0    621.118012          1           40.82     Skill      -1
41  Sparkle    6.0    683.229814          0           76.64     Basic       1
42  Sparkle    0.0     62.111801          6           55.00     Skill      -1
46  Sparkle    0.0    124.223602          1           90.82     Skill      -1
47  Sparkle    0.0    124.323602          0          126.64  Ultimate       4
51  Sparkle    1.0    186.335404          1            5.00     Skill      -1
55  Sparkle    1.0    248.447205          1           40.82     Skill      -1
59  Sparkle    2.0    310.559006          1           76.64     Skill      -1
60  Sparkle    2.0    310.659006          0          112.46  Ultimate       4
64  Sparkle    3.0    372.670807          2            5.00     Skill      -1
68  Sparkle    3.0    434.782609          1           40.82     Skill      -1
72  Sparkle    4.0    496.894410          1           76.64     Skill      -1
73  Sparkle    4.0    496.994410          0          112.46  Ultimate       4
76  Sparkle    5.0    559.006211          3            5.00     Skill      -1
80  Sparkle    5.0    621.118012          1           40.82     Skill      -1
83  Sparkle    6.0    683.229814          0           76.64     Basic       1
84  Sparkle    0.0     62.111801          6           55.00     Skill      -1
88  Sparkle    0.0    124.223602          3           90.82     Skill      -1

In [15]:
spk_ult_df = sparkle_action_df.loc[sparkle_action_df["Action"] == "Ultimate"]

In [16]:
len(spk_ult_df.loc[spk_ult_df["Current Energy"] == 120.00])/len(spk_ult_df)

0.13

In [17]:
action_df.loc[(action_df["Name"] != "Fu Xuan") & (action_df["Name"] != "Silver Wolf")].iloc[:20]

,Name,Cycle,Action Gauge,Current SP,Current Energy,Action,SP Gain
0,Sparkle,0.0,62.111801,6,55.00,Skill,-1
1,Qingque,0.0,62.211801,6,70.00,Enhanced Basic,2
4,Sparkle,0.0,124.223602,4,90.82,Skill,-1
5,Sparkle,0.0,124.323602,3,126.64,Ultimate,4
6,Qingque,0.0,124.323602,7,70.00,Enhanced Basic,3
9,Sparkle,1.0,186.335404,4,5.00,Skill,-1
10,Qingque,1.0,186.435404,3,70.00,Enhanced Basic,2
13,Sparkle,1.0,248.447205,1,40.82,Skill,-1
14,Qingque,1.0,248.547205,0,70.00,Basic,1
17,Sparkle,2.0,310.559006,1,76.64,Skill,-1
18,Sparkle,2.0,310.659006,0,112.46,Ultimate,4
19,Qingque,2.0,310.659006,4,70.00,Enhanced Basic,0
22,Sparkle,3.0,372.670807,2,5.00,Skill,-1
23,Qingque,3.0,372.770807,1,70.00,Enhanced Basic,0
26,Sparkle,3.0,434.782609,1,40.82,Skill,-1
27,Qingque,3.0,434.882609,0,70.00,Basic,1
30,Sparkle,4.0,496.894410,1,76.64,Skill,-1
31,Sparkle,4.0,496.994410,0,112.46,Ultimate,4
32,Qingque,4.0,496.994410,4,70.00,Enhanced Basic,1
34,Sparkle,5.0,559.006211,2,5.00,Skill,-1

In [18]:
statistics_dataframe.df.iloc[:20]

,Sim #,Turn,Cycle,Action Gauge,Current SP,Current Tiles,# Draws,Hidden Hand
0,0,1,0.0,62.211801,6,2,3,True
1,0,2,0.0,124.323602,7,4,4,True
2,0,3,1.0,186.435404,3,4,3,True
3,0,4,1.0,248.547205,0,4,1,False
4,0,5,2.0,310.659006,4,8,1,True
5,0,6,3.0,372.770807,1,4,1,True
6,0,7,3.0,434.882609,0,4,1,False
7,0,8,4.0,496.994410,4,8,2,True
8,0,9,5.0,559.106211,1,3,2,False
9,0,10,5.0,621.218012,0,7,1,False
10,1,1,0.0,62.211801,6,2,6,True
11,1,2,0.0,124.323602,4,4,5,False
12,1,3,1.0,186.435404,0,8,1,False
13,1,4,1.0,248.547205,0,12,1,False
14,1,5,2.0,310.659006,4,16,1,True
15,1,6,3.0,372.770807,1,4,2,False
16,1,7,3.0,434.882609,0,8,1,False
17,1,8,4.0,496.994410,4,12,1,True
18,1,9,5.0,559.106211,2,3,3,False
19,1,10,5.0,621.218012,0,7,1,False

In [19]:
action_df.iloc[:30]

,Name,Cycle,Action Gauge,Current SP,Current Energy,Action,SP Gain
0,Sparkle,0.0,62.111801,6,55.00,Skill,-1
1,Qingque,0.0,62.211801,6,70.00,Enhanced Basic,2
2,Silver Wolf,0.0,68.493151,4,55.00,Skill,-1
3,Fu Xuan,0.0,70.422535,3,67.50,Basic,1
4,Sparkle,0.0,124.223602,4,90.82,Skill,-1
5,Sparkle,0.0,124.323602,3,126.64,Ultimate,4
6,Qingque,0.0,124.323602,7,70.00,Enhanced Basic,3
7,Silver Wolf,0.0,136.986301,4,55.00,Skill,-1
8,Fu Xuan,0.0,140.845070,3,91.38,Basic,1
9,Sparkle,1.0,186.335404,4,5.00,Skill,-1
10,Qingque,1.0,186.435404,3,70.00,Enhanced Basic,2
11,Silver Wolf,1.0,205.479452,1,55.00,Skill,-1
12,Fu Xuan,1.0,211.267606,0,115.26,Basic,1
13,Sparkle,1.0,248.447205,1,40.82,Skill,-1
14,Qingque,1.0,248.547205,0,70.00,Basic,1
15,Silver Wolf,2.0,273.972603,-1,55.00,Basic,1
16,Fu Xuan,2.0,281.690141,0,139.14,Basic,1
17,Sparkle,2.0,310.559006,1,76.64,Skill,-1
18,Sparkle,2.0,310.659006,0,112.46,Ultimate,4
19,Qingque,2.0,310.659006,4,70.00,Enhanced Basic,0
20,Silver Wolf,2.0,342.465753,4,55.00,Skill,-1
21,Fu Xuan,3.0,352.112676,3,163.02,Skill,-1
22,Sparkle,3.0,372.670807,2,5.00,Skill,-1
23,Qingque,3.0,372.770807,1,70.00,Enhanced Basic,0
24,Silver Wolf,3.0,410.958904,1,55.00,Skill,-1
25,Fu Xuan,3.0,422.535211,0,163.02,Basic,1
26,Sparkle,3.0,434.782609,1,40.82,Skill,-1
27,Qingque,3.0,434.882609,0,70.00,Basic,1
28,Silver Wolf,4.0,479.452055,-1,55.00,Basic,1
29,Fu Xuan,4.0,492.957746,0,186.90,Basic,1