In [37]:
import numpy as np
import pandas as pd
from characters.sparkle import Sparkle
from characters.qingque import Qingque
from characters.silver_wolf import Silver_Wolf
from characters.fu_xuan import Fu_Xuan
from simulations.qingque_mono_quantum_looped import QQ_Mono_Quantum, Initialize_QQ_Mono_Quantum
from utils.arena import Arena
from utils.data_table import Action_Table, Qingque_Statistics_Table, Qingque_Probability_Table

# Character Imports

In [38]:
qingque_speed = 98

In [39]:
silver_wolf_speed = 161

In [40]:
sparkle_speed = 160.1
bronya_lc = False
sparkle_tech = True
sparkle_turn_1_skill = True

In [41]:
fu_xuan_speed = 134
fu_xuan_technique = True

# Simulations

In [42]:
arena, qq, spk, sw, fx = Initialize_QQ_Mono_Quantum(qingque_speed=qingque_speed, fu_xuan_speed=fu_xuan_speed, sparkle_speed=sparkle_speed, silver_wolf_speed=silver_wolf_speed, bronya_lc=bronya_lc)

In [43]:
action_dataframe = Action_Table()
statistics_dataframe = Qingque_Statistics_Table()
probability_dataframe = Qingque_Probability_Table()
trials = 100

In [44]:
for run in range(trials):
    print(f"\rRun number = {run}", end='')
    arena, qq, spk, sw, fx = Initialize_QQ_Mono_Quantum(qingque_speed=qingque_speed, fu_xuan_speed=fu_xuan_speed, sparkle_speed=sparkle_speed, silver_wolf_speed=silver_wolf_speed, sparkle_turn_1_skill = sparkle_turn_1_skill)
    QQ_Mono_Quantum(arena, qq, spk, sw, fx, action_df=action_dataframe, stat_df= statistics_dataframe, prob_df = probability_dataframe, run_num=run, cycles=5)

Run number = 1

c:\Users\rainf\OneDrive\Documents\Git Projects\HSR_Action_Simulator-1\utils\data_table.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df = pd.concat([self.df, pd.DataFrame([new_row])], ignore_index = True)
c:\Users\rainf\OneDrive\Documents\Git Projects\HSR_Action_Simulator-1\utils\data_table.py:36: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.df = pd.concat([self.df, pd.DataFrame([new_row])], ignore_index = True)

Run number = 9

Run number = 99

# Results

In [45]:
#statistics_dataframe.df

In [46]:
df = statistics_dataframe.df.copy()
start = df["Turn"].min()
end = df["Turn"].max()
columns = df.columns[1:]
summary_df = pd.DataFrame(columns=columns)
for turn in range(start, end):
    df_copy = df.copy()
    df_turn = df_copy.loc[df["Turn"] == turn]

    new_row_dict = {}
    for col in columns:
        mean = round(df_turn[col].mean(),3)
        std = round(df_turn[col].std(),3)
        if std != 0:
            entry = f"{mean} ± {std}"
        else:
            entry = f"{mean}"
        new_row_dict[col] = [entry]
    new_row = pd.DataFrame.from_dict(new_row_dict)
    summary_df = pd.concat([summary_df, new_row], ignore_index= True)

In [47]:
summary_df_styled = summary_df.style.set_caption(f"Qingque speed = {qingque_speed}, Sparkle speed = {sparkle_speed}, Bronya_LC = {bronya_lc}, Silver Wolf Speed = {silver_wolf_speed}, Fu Xuan speed = {fu_xuan_speed}")
summary_df_styled

In [48]:
action_df = action_dataframe.df

In [49]:
action_df.loc[(action_df["Name"] == "Silver Wolf")].iloc[:20]

           Name  Cycle  Action Gauge Current SP  Current Energy Action SP Gain
0   Silver Wolf    0.0     62.111801          6            55.0  Skill      -1
4   Silver Wolf    0.0    124.223602          4            55.0  Basic       1
9   Silver Wolf    1.0    186.335404          7            55.0  Basic       1
13  Silver Wolf    1.0    248.447205          5            55.0  Skill      -1
17  Silver Wolf    2.0    310.559006          0            55.0  Basic       1
21  Silver Wolf    3.0    372.670807          4            55.0  Basic       1
25  Silver Wolf    3.0    434.782609         -1            55.0  Basic       1
29  Silver Wolf    4.0    496.894410          1            55.0  Skill      -1
33  Silver Wolf    5.0    559.006211          4            55.0  Basic       1
37  Silver Wolf    5.0    621.118012          5            55.0  Basic       1
41  Silver Wolf    0.0     62.111801          6            55.0  Skill      -1
45  Silver Wolf    0.0    124.223602          2            55.0  Basic       1
50  Silver Wolf    1.0    186.335404          6            55.0  Basic       1
54  Silver Wolf    1.0    248.447205          4            55.0  Skill      -1
58  Silver Wolf    2.0    310.559006          2            55.0  Basic       1
62  Silver Wolf    3.0    372.670807          3            55.0  Basic       1
66  Silver Wolf    3.0    434.782609          3            55.0  Skill      -1
70  Silver Wolf    4.0    496.894410          0            55.0  Basic       1
75  Silver Wolf    5.0    559.006211          3            55.0  Basic       1
79  Silver Wolf    5.0    621.118012          2            55.0  Skill      -1

In [50]:
action_df.loc[(action_df["Name"] != "Fu Xuan") & (action_df["Name"] != "Silver Wolf")].iloc[:20]

,Name,Cycle,Action Gauge,Current SP,Current Energy,Action,SP Gain
1,Sparkle,0.0,62.460962,5,55.00,Skill,-1
2,Qingque,0.0,62.560962,5,70.00,Enhanced Basic,2
5,Sparkle,0.0,124.921924,5,90.82,Skill,-1
6,Sparkle,0.0,124.921924,4,126.64,Ultimate,4
7,Qingque,0.0,125.021924,7,70.00,Enhanced Basic,0
10,Sparkle,1.0,187.382886,7,5.00,Skill,-1
11,Qingque,1.0,187.482886,6,70.00,Enhanced Basic,0
14,Sparkle,1.0,249.843848,4,40.82,Skill,-1
15,Qingque,1.0,249.943848,3,70.00,Basic,4
18,Sparkle,2.0,312.304809,1,76.64,Skill,-1
19,Sparkle,2.0,312.304809,0,112.46,Ultimate,4
20,Qingque,2.0,312.404809,4,70.00,Enhanced Basic,0
23,Sparkle,3.0,374.765771,6,5.00,Skill,-1
24,Qingque,3.0,374.865771,5,70.00,Basic,6
26,Sparkle,3.0,437.226733,0,40.82,Basic,1
28,Qingque,4.0,476.906588,2,70.00,Enhanced Basic,1
30,Sparkle,4.0,499.687695,0,76.64,Basic,1
31,Sparkle,4.0,499.687695,1,112.46,Ultimate,4
34,Sparkle,5.0,562.148657,5,5.00,Skill,-1
35,Qingque,5.0,562.248657,4,70.00,Enhanced Basic,0

In [51]:
statistics_dataframe.df.iloc[:20]

,Sim #,Turn,Cycle,Action Gauge,Current SP,Current Tiles,# Draws,Hidden Hand
0,0,1,0.0,62.560962,5,3,3,True
1,0,2,0.0,125.021924,7,4,1,True
2,0,3,1.0,187.482886,6,4,1,True
3,0,4,1.0,249.943848,3,4,4,False
4,0,5,2.0,312.404809,4,8,1,True
5,0,6,3.0,374.865771,5,4,6,False
6,0,7,4.0,476.906588,2,8,2,True
7,0,8,5.0,562.248657,4,6,1,True
8,0,9,5.0,624.709619,5,4,2,True
9,1,1,0.0,62.560962,5,3,5,True
10,1,2,0.0,125.021924,6,4,2,True
11,1,3,1.0,187.482886,6,4,2,True
12,1,4,1.0,249.943848,2,4,2,True
13,1,5,2.0,312.404809,6,4,4,True
14,1,6,3.0,374.865771,4,4,2,True
15,1,7,3.0,437.326733,1,3,2,False
16,1,8,4.0,499.787695,4,7,1,True
17,1,9,5.0,562.248657,3,4,3,True
18,1,10,5.0,624.709619,0,4,1,False
19,2,1,0.0,62.560962,5,3,3,True